version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14.3
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    environment:
      GO111MODULE: on
    steps:
      - checkout
      - run: go mod tidy
      - run: go mod vendor
      - run: go test -v -count=1 -race ./...
