#!/bin/bash

set -o errexit

DIR="$(dirname "$0")"
. "${DIR}/config"


for i in $(eval echo "{1..$NUMBER_OF_INSTANCES}")
do
    echo "deploying ${DEVICE_NAME_PREFIX}-${i}..."
    az container create \
        --name "${DEVICE_NAME_PREFIX}-${i}" \
        --image "mchmarny/eventmaker:${IMAGE_VERSION}" \
        --cpu 1 \
        --memory 1 \
        --os-type Linux \
        --environment-variables CONN_STR=${CONN_STR} DEV_NAME="${DEVICE_NAME_PREFIX}-${i}" \
        --command-line "/eventmaker --metric '${METRIC_TEMPLATE}'" \
        --no-wait
done


